# Setup
title:        Green Up Day Worldwide
tagline:      Let's get to work
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Matt
  url:        https://github.com/mattbk

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
